/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sabina B. Heyford
 */
public class newofficerrecord extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public newofficerrecord() {
        initComponents();
    }
    
    
        
     Connection Con = null;
     Statement St = null;
     java.sql.ResultSet Rs = null;
      public void SelectProd()
    {
        try{
            Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/crimerecord","root","");
            St = (Statement) Con.createStatement();
            Rs = (java.sql.ResultSet) St.executeQuery("select * from policerecord");
            table.setModel(DbUtils.resultSetToTableModel((java.sql.ResultSet) Rs));
        }catch(java.sql.SQLException e)
        {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        stfirst = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        forth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fifth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nineth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eighth = new javax.swing.JTextField();
        seventh = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sixth = new javax.swing.JTextField();
        forteenth = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        twelveth = new javax.swing.JTextField();
        tenth = new javax.swing.JTextField();
        thirteenth = new javax.swing.JTextField();
        eleventh = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        second = new javax.swing.JTextField();
        third = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRIME RECORDS MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel2)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1065, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        jLabel1.setText("NEW RECORD INSERTION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 38));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 770, -1, -1));

        stfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stfirstActionPerformed(evt);
            }
        });
        jPanel1.add(stfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 560, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel4.setText("POLICE NO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        forth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forthActionPerformed(evt);
            }
        });
        jPanel1.add(forth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 560, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel5.setText("NAME:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 60, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel6.setText("DESIGNATION:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel7.setText("GENDER:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, -1));

        fifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifthActionPerformed(evt);
            }
        });
        jPanel1.add(fifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 560, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel8.setText("DATE OF BIRTH:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel9.setText("CITY:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        nineth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninethActionPerformed(evt);
            }
        });
        jPanel1.add(nineth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 560, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel10.setText("STREET:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel11.setText("EMAIL:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        eighth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eighthActionPerformed(evt);
            }
        });
        jPanel1.add(eighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 560, -1));

        seventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seventhActionPerformed(evt);
            }
        });
        jPanel1.add(seventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 560, -1));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel12.setText("PHONE NO:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 80, -1));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel13.setText("DATE OF JOINING:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        sixth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixthActionPerformed(evt);
            }
        });
        jPanel1.add(sixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 560, -1));

        forteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forteenthActionPerformed(evt);
            }
        });
        jPanel1.add(forteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 560, -1));

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel15.setText("FLAT NO:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, -1, -1));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel16.setText("PIN CODE:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel17.setText("COUNTRY:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jLabel18.setText("REGION:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 70, -1));

        twelveth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelvethActionPerformed(evt);
            }
        });
        jPanel1.add(twelveth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 560, -1));

        tenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenthActionPerformed(evt);
            }
        });
        jPanel1.add(tenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 560, -1));

        thirteenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirteenthActionPerformed(evt);
            }
        });
        jPanel1.add(thirteenth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 560, -1));

        eleventh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleventhActionPerformed(evt);
            }
        });
        jPanel1.add(eleventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 560, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 240, 40));

        second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondActionPerformed(evt);
            }
        });
        jPanel1.add(second, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 560, -1));

        third.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdActionPerformed(evt);
            }
        });
        jPanel1.add(third, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stfirstActionPerformed

    private void forthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forthActionPerformed

    private void fifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fifthActionPerformed

    private void ninethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninethActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ninethActionPerformed

    private void eighthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eighthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eighthActionPerformed

    private void seventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seventhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seventhActionPerformed

    private void sixthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixthActionPerformed

    private void forteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forteenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forteenthActionPerformed

    private void twelvethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelvethActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twelvethActionPerformed

    private void tenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenthActionPerformed

    private void thirteenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirteenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirteenthActionPerformed

    private void eleventhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleventhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eleventhActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                try{ 
          
            Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/crimerecord","root","");
            PreparedStatement add = (PreparedStatement) Con.prepareStatement("insert into policerecord values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            add.setInt(1,Integer.parseInt(stfirst.getText()));
            add.setString(2,second.getText());
            add.setString(3,third.getText());
            add.setString(4,forth.getText());
            add.setString(5,fifth.getText());
            add.setString(6,sixth.getText());
            add.setString(7,seventh.getText());
            add.setString(8,eighth.getText());
            add.setString(9,nineth.getText());
            add.setString(10,tenth.getText());
            add.setString(11,eleventh.getText());
            add.setString(12,twelveth.getText());
            add.setString(13,thirteenth.getText());
            add.setString(14,forteenth.getText());

            
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record sessfully Addded");
            Con.close();
            }catch(java.sql.SQLException e)
        {
          
          System.out.println(e.getMessage()); 
       }

        menu ad = new menu();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondActionPerformed

    private void thirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newofficerrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newofficerrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newofficerrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newofficerrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newofficerrecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eighth;
    private javax.swing.JTextField eleventh;
    private javax.swing.JTextField fifth;
    private javax.swing.JTextField forteenth;
    private javax.swing.JTextField forth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nineth;
    private javax.swing.JTextField second;
    private javax.swing.JTextField seventh;
    private javax.swing.JTextField sixth;
    private javax.swing.JTextField stfirst;
    private javax.swing.JTextField tenth;
    private javax.swing.JTextField third;
    private javax.swing.JTextField thirteenth;
    private javax.swing.JTextField twelveth;
    // End of variables declaration//GEN-END:variables
}
